# base node image
FROM node:18-bullseye-slim as base

# install openssl and sqlite3 for prisma
RUN apt-get update && apt-get install -y openssl sqlite3 fuse3

# install all node_modules, including dev
FROM base as deps

RUN mkdir /app/
WORKDIR /app/

ADD package.json package-lock.json ./
RUN npm install

# build app
FROM base as build

RUN mkdir /app/
WORKDIR /app/

COPY --from=deps /app/node_modules /app/node_modules

# schema doesn't change much so these will stay cached
ADD prisma /app/prisma
RUN npx prisma generate

# app code changes all the time
ADD . .
RUN npm run build

# build smaller image for running
FROM base

ENV DATABASE_URL="file:/data/litefs/sqlite.db"
ENV INTERNAL_PORT="8080"
ENV PORT="8081"
ENV NODE_ENV="development"

RUN mkdir /app/
WORKDIR /app/

COPY --from=deps /app/node_modules /app/node_modules

COPY --from=build /app/node_modules/.prisma /app/node_modules/.prisma
COPY --from=build /app/server-build /app/server-build
COPY --from=build /app/build /app/build
COPY --from=build /app/public /app/public
COPY --from=build /app/prisma /app/prisma

ADD . .

RUN npx prisma migrate dev

CMD ["npm", "run", "dev"]
